### ISSUE TITLE
Pathing on OSX

### ISSUE THREAD

**Issue by bright-star** [sindresorhus/fkill-cli#10]
Is `/usr/local/lib` expected to be in the user's path? 

```
~ » npm install -g fkill
/usr/local/lib
└── fkill@4.1.0

~ » which fkill

```

**Comment by Daniel15** [comment]
It should put an executable in `/usr/local/bin/`, which should be on your path. This is the behaviour on Linux, I don't have a Mac OS computer to test.

**Comment by bright-star** [comment]
Yeah, I don't know if this is an npm thing or not. Indeed, the OSX path looks something like `/usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin`. I tried yarn and got a similar result:

```
~ » yarn global add fkill
yarn global v0.21.3
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
warning undefined has no binaries
warning No license field
✨  Done in 7.10s.
```

**Comment by zcong1993** [comment]
you should export yarn or npm global bin path to your `PATH Variable` or `shell profile`, the path of yarn is `$HOME/.yarn/bin`

**Comment by bright-star** [comment]
Yeah, that was already in my config file

**Comment by zcong1993** [comment]
maybe you can try `$HOME/.yarn/bin`

**Comment by bright-star** [comment]
Still with you there:

```
# Path to Oh My Fish install.
set -gx OMF_PATH "/Users/user/.local/share/omf"

# Customize Oh My Fish configuration path.
#set -gx OMF_CONFIG "/Users/user/.config/omf"

set -x LC_ALL ja_JP.UTF-8  
set -x LANG ja_JP.UTF-8

set -x GOPATH $HOME
set -x PATH $PATH $GOPATH/bin
set -x PATH $PATH $HOME/.multirust/toolchains/stable/cargo/bin/
set -x PATH $HOME/.yarn/bin $PATH
set -x PATH $PATH (yarn global bin)
```

**Comment by yannbertrand** [comment]
I think you installed the wrong package. You need to install `fkill-cli` to use `fkill` in a terminal. The `[fkill](https://github.com/sindresorhus/fkill)` package is only the API for this module.

**Comment by shinnn** [comment]
Yes @yannbertrand is right. Try `npm i -g fkill-cli` and you'll be able to use `fkill` comamnd.
