### ISSUE TITLE
Show context

### ISSUE THREAD

**Issue by knownasilya** [sindresorhus/fkill-cli#13]
Either the path or full command for the running process. This helps differentiate between two or more processes with the same name.

This could be a flag, like `fkill --detailed`.

**Comment by coffeedoughnuts** [comment]
This was my first instinct when I saw this tool - would be great to search based on arguments.

It was trivial to implement - my PR is here: #14

**Comment by sparty02** [comment]
See https://github.com/sindresorhus/fkill-cli/issues/6#issuecomment-282637495 which could solve this too.
