### ISSUE TITLE
Add navigation with cltrl-n / ctrl-p

### ISSUE THREAD

**Issue by lfv89** [sindresorhus/fkill-cli#15]
Not everyone likes to use the arrow keys!

Thanks for this tool by the way.

**Comment by SamVerschueren** [comment]
It uses [Inquirer.js](https://github.com/SBoudrias/Inquirer.js/) to render the list and allow you to navigate up or down. So I guess you should add a feature request over there.

**Comment by sindresorhus** [comment]
If anyone comes here in the future and wants this, do what Sam said, and open an issue on Inquirer.js
