### ISSUE TITLE
processes list [enhancement]

### ISSUE THREAD

**Issue by shoully** [sindresorhus/fkill-cli#2]
What if : 

`$ fkill --list`

   display all running processes in simple screen, unlike **top** in OSX

**Comment by sindresorhus** [comment]
Duplicate of #1?

**Comment by shoully** [comment]
No, I'm not saying it should be interactive, it's lit "ps" command in Mac OS or "top", but in nice list

**Comment by sindresorhus** [comment]
Try out the latest version. By running `$ fkill` you start the interactive interface with a list of processes. Let us know if there's anything we can improve about it ;)
