### ISSUE TITLE
Process name display incomplete

### ISSUE THREAD

**Issue by jingle0927** [sindresorhus/fkill-cli#35]
deepin 15.5 
![_ _20180316131325](https://user-images.githubusercontent.com/26103116/37504857-2d981f8c-291c-11e8-8642-cf0bae578e08.png)

**Comment by kevva** [comment]
What's the intended output in this case?

**Comment by jingle0927** [comment]
deepin-notifications
deepin-cloud-printer

@kevva

**Comment by jingle0927** [comment]
`top`

also display incomplete , search the name of the top process?

**Comment by sindresorhus** [comment]
Yes, this has stumped me for a long time: https://github.com/sindresorhus/ps-list/issues/1

Help appreciated if anyone knows a way to do it.
