### ISSUE TITLE
The terminal interface

### ISSUE THREAD

**Issue by z4jst** [sindresorhus/fkill-cli#41]
Hello, 

I saw u got a nice terminal interface in README, I really love it.
Would u mind tell me what u theme is or tool is?.

Thanks ~

**Comment by xflife** [comment]
@sindresorhus i want it,too.thks.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ama/issues/458

**Comment by z4jst** [comment]
Thanks a lot !
