### ISSUE TITLE
PATH

### ISSUE THREAD

**Issue by superandrew** [sindresorhus/fkill-cli#43]
I installed it following instructions, and it was installed in /usr/local/Cellar/node/8.9.1/bin/fkill. I don't have this into my PATH variable, should I add it or did I do something wrong?

**Comment by sindresorhus** [comment]
I would recommend using a Node.js version manager instead of Brew for installing Node.js. For example https://github.com/tj/n

Also see: https://gist.github.com/DanHerbert/9520689

This is not really an issue with this package, but rather your Node.js setup.
