### ISSUE TITLE
Can it kill a 'Google Chrome Helper'? 

### ISSUE THREAD

**Issue by rupertqin** [sindresorhus/fkill-cli#48]

**Comment by sindresorhus** [comment]
Yes, I'm using the underlaying `fkill` package in my [`kill-tabs`](https://github.com/sindresorhus/kill-tabs) package.

**Comment by rupertqin** [comment]
@sindresorhus  I need a feature,  just to kill that  'Google Chrome Helper's take Memories over than 300M
