### ISSUE TITLE
Better fuzzy search

### ISSUE THREAD

**Issue by mourner** [sindresorhus/fkill-cli#49]
In the interactive mode, entering e.g. "crome" (instead of "chrome") will show "No results...". It would be great to improve the UI to be better at fuzzy search, e.g. with the help of https://github.com/farzher/fuzzysort

**Comment by sindresorhus** [comment]
👍 Yeah, that would be useful.

Maybe @Sunshine168 wants to handle that in the rewrite.

**Comment by Sunshine168** [comment]
Yes , it will improve searching , i will try to implement it
