### ISSUE TITLE
Cannot install on Ubuntu

### ISSUE THREAD

**Issue by PrzemekSkw** [sindresorhus/fkill-cli#57]
I try to install on Ubuntu 18.10 and have errors:

> 
npm install --global fkill-cli                                                                                                                                                                
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN checkPermissions Missing write access to /usr/local/lib
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/przemek/.npm/_logs/2018-11-07T09_48_04_973Z-debug.log

**Comment by sindresorhus** [comment]
That error message is coming from npm. Use https://npm.community/ for npm install support.
