### ISSUE TITLE
Combining --force and --silent

### ISSUE THREAD

**Issue by thinkofapps** [sindresorhus/fkill-cli#64]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/fkill-cli/issues/64)

We need to kill a node process that runs a server (e.g. on port 8000) as part of our deployment script.

Using "fkill :8000" doesn't terminate the process, so we need "fkill -f :8000"

Unfortunately, fkill is returning an error code when there is no process running on port 8000. So we added the silent switch "fkill -f -s :8000"

This works, but gives an error message when no process has been found, which should not be the case using -s.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#65 Combining --force and --silent #64](https://issuehunt.io/r/sindresorhus/fkill-cli/pull/65)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/fkill-cli/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
Yeah, that's a bug. It should work like you describe. PR welcome :)

**Comment by ulken** [comment]
I looked into this. I wasn't able to reproduce it when cloning the repository. However, when installing it from `npm`, it did indeed fail as described.

**Reason:** `npm` is not up-to-date with the repository. To be more precise, dependencies have been updated and [`fkill`](https://github.com/sindresorhus/fkill-cli/commit/10767178af49357462fbdb3de796b6d9eb3993d1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R46) in particular. Version [`6.2.0`](https://github.com/sindresorhus/fkill/releases/tag/v6.2.0) introduced support for the `silent` option in `fkill` which fixes this issue.

**Fix:** Publish a new version with the current repository state to `npm`

**Comment by ulken** [comment]
@sindresorhus Thoughts on the above?

**Comment by sindresorhus** [comment]
@ulken The bounty is yours if you submit a test that shows that it's already fixed.

**Comment by ulken** [comment]
@sindresorhus ✅
