### ISSUE TITLE
Process list not displaying application names

### ISSUE THREAD

**Issue by rmtsrc** [sindresorhus/fkill-cli#78]
Running `fkill` does not display the application names only part of the folder for example:

![Screenshot 2021-01-15 at 21 38 51](https://user-images.githubusercontent.com/144435/104782171-b093c400-577b-11eb-9de3-96e121b5a6d5.png)

**Comment by arkdelkaos** [comment]
I'm having the same issue...
Mac
`ProductName:	macOS`
`ProductVersion:	11.2`
`BuildVersion:	20D64`
Shell running with `zsh 5.8 (x86_64-apple-darwin20.0)`
`Node v14.15.4` with `NPM 6.14.11`

**Comment by dennismphil** [comment]
Same here.. After I upgraded to macOS Bigsur, started showing up like this.

![](https://user-images.githubusercontent.com/4141366/128274777-7b182b44-e195-48c6-a309-740d579501a7.png)

**Comment by rthangam** [comment]
I too face the same issue fkill -v provides a alternative but would be good to fix this one
