### ISSUE TITLE
how to close properly?

### ISSUE THREAD

**Issue by galambalazs** [sindresorhus/fkill-cli#8]
Awesome stuff.

But `Ctrl + C` on my Mac leaves a residue of the fkill interface (which can only be cleared if I issue new commands or hit Enter for a few times to clear all those lines).

how to close fkill properly?

**Comment by sindresorhus** [comment]
Can you share a screenshot of how it looks?
Probably an [Inquirer.js](https://github.com/SBoudrias/Inquirer.js) (the lib used for creating the interactive menu).

**Comment by galambalazs** [comment]
<img width="722" alt="screen shot 2016-02-23 at 08 52 07" src="https://cloud.githubusercontent.com/assets/309987/13245070/cca08e88-da0a-11e5-83c4-18e19d70bd9e.png">

**Comment by sindresorhus** [comment]
What Node.js version are you on? Does the same thing happen if you press Esc (you might have to press it multiple times to quit because of a Node.js bug).

**Comment by galambalazs** [comment]
Yes same with Esc. 
Node 4.3.1 LTS

**Comment by galambalazs** [comment]
Doesn't happen for you?

(happens for me both on my local Mac or on servers I SSH into)

**Comment by sindresorhus** [comment]
> Doesn't happen for you?

Yes, but in a different way.

Anyways, I think I tracked it down. With this I can no longer reproduce it: https://github.com/mokkabonna/inquirer-autocomplete-prompt/pull/14

**Comment by galambalazs** [comment]
:+1:

**Comment by mokkabonna** [comment]
PR up for fixing this now: https://github.com/SBoudrias/Inquirer.js/pull/497

**Comment by mokkabonna** [comment]
Required PR now merged https://github.com/SBoudrias/Inquirer.js/pull/500

So whenever that is released it will be working.
