### ISSUE TITLE
Search doesn't find process

### ISSUE THREAD

**Issue by loureirorg** [sindresorhus/fkill-cli#85]
First of all, thanks for the amazing tool. 

I recently started using `fkill`, but I'm not sure if I'm doing it wrong or what.

I have this `Hubstaff` process that I'm trying to kill:
![fkill-cant-find](https://user-images.githubusercontent.com/371973/200625086-4b7077c9-5de6-40c8-9ccb-8a20d27264e2.png)

But the search can't find it.

I also searched by its process ID without any luck:
![fkill-cant-find-by-process](https://user-images.githubusercontent.com/371973/200625286-11cb2b32-8571-450e-9725-380135c73d67.png)

But when I run `fkill -v` I can see the process. Although I have to search it by its full path.

Am I searching wrong?

**Comment by sindresorhus** [comment]
The name became truncated at some point. I haven't had time to look into it.

**Comment by loureirorg** [comment]
I see. Glad to know it is in the pipeline for the next version. Thanks!
